version: '3'

services:
  postgresql:
    image: postgres
    ports:
      - '5432:5432'
    container_name: 'postgresql'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

volumes:
  pg-data: